export const StandardData = [
  {
    id: 0,
    src: "https://images-eu.nivea.com/-/media/local/de/schoene-haut/augenringe-0180/niveax/cam_augenringe_keyvisual.webp?rx=0&ry=0&rw=2702&rh=1500&mw=383&hash=4F6477145151FAA03BB4FBF00406D56E",
    subline: "Gesicht",
    headline: "Was hilft gegen Augenringe und wie entstehen sie?",
    dsc: "Schatten unter den Augen haben unterschiedliche Ursachen. Lesen Sie hier, wie sie entstehen und was Sie dagegen tun können.",
    link: "Weiterlesen",
  },
  {
    id: 1,
    src: "https://images-eu.nivea.com/-/media/local/de/schoene-haare/luftige-sommerfrisuren/thumbnail-luftige-sommerfrisuren-neu.webp?rx=0&ry=0&rw=590&rh=327&mw=383&hash=83C3B0606A4E7DA79AD408F79CA2A6BC",
    subline: "Gesicht",
    headline: "Was hilft gegen Augenringe und wie entstehen sie?",
    dsc: "Schatten unter den Augen haben unterschiedliche Ursachen. Lesen Sie hier, wie sie entstehen und was Sie dagegen tun können.",
    link: "Weiterlesen",
  },
  {
    id: 2,
    src: "https://images-eu.nivea.com/-/media/local/de/schoene-haut/gesunde-ernaehrung-0213/gesunde-ernaehrung-thumbnail.webp?rx=0&ry=0&rw=590&rh=327&mw=383&hash=C270C0BB8B48B370C4C41C0CBC292B4C",
    subline: "Gesicht",
    headline: "Was hilft gegen Augenringe und wie entstehen sie?",
    dsc: "Schatten unter den Augen haben unterschiedliche Ursachen. Lesen Sie hier, wie sie entstehen und was Sie dagegen tun können.",
    link: "Weiterlesen",
  },
  {
    id: 3,
    src: "https://images-eu.nivea.com/-/media/local/de/lifestyle/wimpernpflege-tipps-fuer-gesunde-und-schoene-wimpern/wimpernpflege-tipps-fuer-gesunde-und-schoene-wimpern_thumbnail.webp?rx=0&ry=0&rw=590&rh=327&mw=383&hash=241BB3D7943A6A3857EB0B8E13A15D2F",
    subline: "Gesicht",
    headline: "Was hilft gegen Augenringe und wie entstehen sie?",
    dsc: "Schatten unter den Augen haben unterschiedliche Ursachen. Lesen Sie hier, wie sie entstehen und was Sie dagegen tun können.",
    link: "Weiterlesen",
  },
  {
    id: 4,
    src: "https://images-eu.nivea.com/-/media/local/de/inspiration/geschenke-selber-machen-basteln-und-backen-fuer-ihre-liebsten/geschenke-selber-machen-thumbnail.webp?rx=0&ry=0&rw=590&rh=327&mw=383&hash=A31C41A594FFE4366E468DA6F8195A73",
    subline: "Gesicht",
    headline: "Was hilft gegen Augenringe und wie entstehen sie?",
    dsc: "Schatten unter den Augen haben unterschiedliche Ursachen. Lesen Sie hier, wie sie entstehen und was Sie dagegen tun können.",
    link: "Weiterlesen",
  },
  {
    id: 5,
    src: "https://images-eu.nivea.com/-/media/local/de/baby/baby-fingernaegel-schneiden-sanft-und-sicher/baby-fingernaegel-schneiden-thumbnail.webp?rx=0&ry=0&rw=590&rh=327&mw=383&hash=02F6E753C19E523753BD9544C20CE1E1",
    subline: "Gesicht",
    headline: "Was hilft gegen Augenringe und wie entstehen sie?",
    dsc: "Schatten unter den Augen haben unterschiedliche Ursachen. Lesen Sie hier, wie sie entstehen und was Sie dagegen tun können.",
    link: "Weiterlesen",
  },
  {
    id: 6,
    src: "https://images-eu.nivea.com/-/media/global/advice/nice-skin/bb-cream-9/bb-cream-thumbnail.webp?rx=0&ry=76&rw=590&rh=327&mw=383&hash=F7E0EF2A83C78BED0EF26EF526E106F2",
    subline: "Gesicht",
    headline: "Was hilft gegen Augenringe und wie entstehen sie?",
    dsc: "Schatten unter den Augen haben unterschiedliche Ursachen. Lesen Sie hier, wie sie entstehen und was Sie dagegen tun können.",
    link: "Weiterlesen",
  },
  {
    id: 7,
    src: "https://images-eu.nivea.com/-/media/local/de/schoene-haut/kopfhaut-pflegen/kopfhaut-pflegen-thumbnail.webp?rx=0&ry=0&rw=590&rh=327&mw=383&hash=F0DDBF8E3372AA169B1842F4C7D35CD9",
    subline: "Gesicht",
    headline: "Was hilft gegen Augenringe und wie entstehen sie?",
    dsc: "Schatten unter den Augen haben unterschiedliche Ursachen. Lesen Sie hier, wie sie entstehen und was Sie dagegen tun können.",
    link: "Weiterlesen",
  },
  {
    id: 8,
    src: "https://images-eu.nivea.com/-/media/local/de/schoene-haare/naturhaarfarbe/zurueck-zur-naturhaarfarbe-thumbnail.webp?rx=0&ry=0&rw=590&rh=327&mw=383&hash=D3FD4933F0C8FA3298D1DBF6C06F3089",
    subline: "Gesicht",
    headline: "Was hilft gegen Augenringe und wie entstehen sie?",
    dsc: "Schatten unter den Augen haben unterschiedliche Ursachen. Lesen Sie hier, wie sie entstehen und was Sie dagegen tun können.",
    link: "Weiterlesen",
  },
];
